# Generated by Django 3.2.9 on 2022-05-15 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConstants',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('site_name', models.CharField(blank=True, default='Splinr', max_length=100, null=True)),
                ('theme_color', models.CharField(blank=True, default='#EF3724', max_length=100, null=True)),
                ('site_url', models.URLField(blank=True, default='https://devme.com', null=True)),
                ('description', models.TextField(blank=True, default='Description about devme.', null=True)),
                ('key_words', models.TextField(blank=True, default='web design', null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='phone')),
                ('working_days', models.CharField(blank=True, default='mon-fri', max_length=250, null=True)),
                ('site_content', models.CharField(blank=True, max_length=250, null=True)),
                ('working_hours', models.CharField(blank=True, default='8am-10pm', max_length=250, null=True)),
                ('closed_days', models.CharField(blank=True, default='sun', max_length=250, null=True)),
                ('special_days', models.CharField(blank=True, default='sat & holidays', max_length=250, null=True)),
                ('special_hours', models.CharField(blank=True, default='8am-12pm', max_length=250, null=True)),
                ('favicon', models.ImageField(blank=True, default='favicon.ico', null=True, upload_to='logo/')),
                ('icon_180', models.ImageField(blank=True, default='favicon-180x180.png', null=True, upload_to='logo/')),
                ('icon_32', models.ImageField(blank=True, default='favicon-32x32.png', null=True, upload_to='logo/')),
                ('icon_16', models.ImageField(blank=True, default='favicon-16x16.png', null=True, upload_to='logo/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'site_constants',
                'db_table': 'site_constants',
            },
        ),
    ]
