# Generated by Django 3.2.9 on 2022-05-23 18:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconstants',
            name='address',
            field=models.CharField(blank=True, default='Moi University,Kesses, Eldoret Uasin Gishu County Kenya', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='description',
            field=models.TextField(blank=True, default='Admino description.', null=True),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='favicon',
            field=models.ImageField(blank=True, default='favicon.ico', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='icon_16',
            field=models.ImageField(blank=True, default='favicon-16x16.png', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='icon_180',
            field=models.ImageField(blank=True, default='favicon-180x180.png', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='icon_32',
            field=models.ImageField(blank=True, default='favicon-32x32.png', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='key_words',
            field=models.TextField(blank=True, default='sample keywords', null=True),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='location',
            field=models.CharField(blank=True, default='Eldoret,Kenya ', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+254798449624', max_length=128, null=True, region=None, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='site_name',
            field=models.CharField(blank=True, default='Armlogi', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='site_url',
            field=models.URLField(blank=True, default='https://admino.com', null=True),
        ),
        migrations.AlterField(
            model_name='siteconstants',
            name='theme_color',
            field=models.CharField(blank=True, default='#222342', max_length=100, null=True),
        ),
    ]
