# Generated by Django 3.2.9 on 2022-05-18 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedAdmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('main', models.BooleanField(default=False)),
                ('is_installed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'extended_admins',
                'db_table': 'extended_admin',
            },
        ),
        migrations.CreateModel(
            name='ExtendedAuthUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='phone')),
                ('initials', models.CharField(blank=True, max_length=10, null=True)),
                ('bgcolor', models.CharField(blank=True, default=manager.models.bgcolor, max_length=10, null=True)),
                ('company', models.CharField(blank=True, default='Armlogi', max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profiles/placeholder.jpg', null=True, upload_to='profiles/')),
                ('role', models.CharField(blank=True, choices=[('tertiary', 'View only'), ('secondary', 'View | Edit'), ('primary', 'View | Edit | Invoice')], max_length=200, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'extended_auth_users',
                'db_table': 'extended_auth_user',
                'permissions': (('can_view', 'Can view'), ('can_edit', 'Can edit'), ('can_see_invoice', 'Can see invoice')),
            },
        ),
        migrations.CreateModel(
            name='Oders',
            fields=[
                ('ordername_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordername', models.CharField(max_length=50, null=True, verbose_name='ordername')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentifier', models.CharField(default=manager.models.generate_id, max_length=100)),
                ('load', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('pierpass', models.CharField(blank=True, max_length=100, null=True)),
                ('mbl', models.CharField(blank=True, max_length=100, null=True)),
                ('hbl', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('container', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('seal', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_city', models.CharField(blank=True, max_length=100, null=True)),
                ('discharge_port', models.CharField(blank=True, max_length=100, null=True)),
                ('port_eta', models.CharField(blank=True, max_length=100, null=True)),
                ('lfd', models.CharField(blank=True, max_length=100, null=True)),
                ('trucking', models.CharField(blank=True, max_length=100, null=True)),
                ('east_deliver', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment', models.CharField(blank=True, max_length=100, null=True)),
                ('actual_deliver', models.CharField(blank=True, max_length=100, null=True)),
                ('driver', models.CharField(blank=True, max_length=100, null=True)),
                ('empty_return', models.CharField(blank=True, max_length=100, null=True)),
                ('chasis', models.CharField(blank=True, max_length=100, null=True)),
                ('demurrage', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_sent', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_dolla', models.CharField(blank=True, max_length=100, null=True)),
                ('a_rrry', models.CharField(blank=True, max_length=100, null=True)),
                ('a_ppy', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('notify', models.CharField(blank=True, max_length=100, null=True)),
                ('acct_email', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.oders')),
            ],
            options={
                'verbose_name_plural': 'orderfields',
                'db_table': 'orderfields',
            },
        ),
    ]
