# Generated by Django 3.2.9 on 2022-05-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedauthuser',
            name='prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
