# Generated by Django 3.2.9 on 2022-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfields',
            name='status',
            field=models.CharField(blank=True, choices=[('cancelled_pickup', 'Cancelled pickup'), ('on_ship', 'On ship'), ('invoice_sent', 'Invoice sent'), ('closed_area', 'Closed area'), ('assigned_driver', 'Assigned driver'), ('delivered', 'Delivered'), ('do_recd', 'Do Recd')], max_length=255, null=True),
        ),
    ]
