# Generated by Django 3.2.9 on 2022-05-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_extendedauthuser_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendedauthuser',
            name='prefix',
        ),
    ]
