# Generated by Django 3.2.9 on 2022-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_extendedauthuser_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfields',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
