# Generated by Django 3.2.9 on 2022-05-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_userfileuploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfileuploads',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
