# Generated by Django 3.2.9 on 2022-05-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_userfileuploads_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfields',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
