# Generated by Django 3.2.9 on 2022-05-20 18:45

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_orderfields_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oders',
            name='ordername_serial',
            field=models.CharField(default=manager.models.generate_serial, max_length=255),
        ),
        migrations.AddField(
            model_name='userfileuploads',
            name='ordername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extendedauthuser',
            name='role',
            field=models.CharField(blank=True, choices=[('tertiary', 'View only'), ('secondary', 'View | Edit'), ('admin', 'View | Edit | Invoice | Admin')], max_length=200, null=True),
        ),
    ]
