# Generated by Django 3.2.9 on 2022-05-20 19:55

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20220520_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfields',
            name='intentifier',
        ),
        migrations.AlterField(
            model_name='orderfields',
            name='load',
            field=models.CharField(default=manager.models.generate_id, max_length=100),
        ),
    ]
