# Generated by Django 3.2.9 on 2022-05-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20220520_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfileuploads',
            name='order_indentity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
