# Generated by Django 3.2.9 on 2022-05-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_orderfields_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedauthuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='profiles/'),
        ),
    ]
