# Generated by Django 3.2.9 on 2022-05-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_extendedauthuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedauthuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Tertiary', 'View only'), ('Secondary', 'View | Edit')], max_length=200, null=True),
        ),
    ]
