# Generated by Django 3.2.9 on 2022-05-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_extendedauthuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfields',
            old_name='media',
            new_name='usermedia',
        ),
        migrations.AlterField(
            model_name='extendedauthuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Tertiary', 'View only'), ('Secondary', 'View | Edit'), ('Admin', 'View | Edit  | Admin')], max_length=200, null=True),
        ),
    ]
