# Generated by Django 3.2.9 on 2022-05-25 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_rename_usermedia_orderfields_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfields',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
