# Generated by Django 3.2.9 on 2022-05-25 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_orderfields_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfields',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'orderfields'},
        ),
        migrations.AddField(
            model_name='orderfields',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
